CREATE DATABASE ECOMMERCE;

USE ECOMMERCE;

CREATE TABLE TRANSAC (     --SYNTAX FOR CREATING AN EMPTY TABLE , SPECIFY THE NAME OF THE TABLE NAME
TNXID INT PRIMARY KEY, --ASSIGN APPROPRIATE DATATYPES TO THE COLUMNS CREATED (BASICALLY WHAT TYPE OF DATA YOU WANT TO STORE)
PRODUCTID VARCHAR(255),
PRODUCTDESC VARCHAR(255),
PRICE FLOAT
);

INSERT INTO TRANSAC       --FILL IN INFORMATION INTO THE TABLE CREATED (HERE ITS TRANSACACION TABLE)
VALUES                  -- ALL VALUES SHOULD BE STORED IN ORDER OF THE COLUMN NAMES
(1001,'P1','TSHIRT',100.50), -- DATATYPES OF THE COLUMNS AND THE VALUES IN IT SHOULD BE SAME
(1002,'P2','SHIRT',50),
(1003,'P3','PANT',40),
(1004,'P4','SAREE',120),
(1005,'P5','TOP',110),
(1006,'P6','TSHIRT',60),
(1007,'P1','TSHIRT',90),
(1008,'P3','PANT',50),
(1009,'P7','TSHIRT',70)
;


SELECT * FROM TRANSAC;    --VIEW THE ENTIRE TABLE WITH ALL THE INFORMATION/DATA

--USE TRANSAC;
ALTER TABLE TRANSAC ADD DISCOUNT INT ;
--ALTER TABLE TRANSAC ADD QTY INT AFTER PRODUCTDESC;

--ALTER TABLE TRANSAC RENAME DISCOUNT TO DISC_PEC;  MYSQL SYNTAX
EXEC SP_RENAME 'TRANSAC.DISCOUNT', 'DISC_PEC', 'COLUMN';  --SQL SERVER SYNTAX

--Alter table table_name modify column column_name varchar(30);  MYSQL SYNTAX
-- ALTER TABLE dbo.TRANSAC ALTER COLUMN TNXID VARCHAR (255);


UPDATE TRANSAC SET DISC_PEC=10 WHERE TNXID=1001;
UPDATE TRANSAC SET DISC_PEC=15 WHERE TNXID=1002;
UPDATE TRANSAC SET DISC_PEC=5 WHERE TNXID=1003;
UPDATE TRANSAC SET DISC_PEC=20 WHERE TNXID=1004;
UPDATE TRANSAC SET DISC_PEC=8 WHERE TNXID=1005;
UPDATE TRANSAC SET DISC_PEC=12 WHERE TNXID=1006;
UPDATE TRANSAC SET DISC_PEC=11 WHERE TNXID=1007;
UPDATE TRANSAC SET DISC_PEC=15 WHERE TNXID=1008;
UPDATE TRANSAC SET DISC_PEC=5 WHERE TNXID=1009;


SELECT TRANSAC.TNXID, TRANSAC.PRODUCTDESC FROM TRANSAC;

SELECT TOP 2 * FROM TRANSAC;
--SELECT * FROM TRANSAC LIMIT 2;

SELECT * FROM TRANSAC WHERE PRICE>=50;

SELECT PRODUCTDESC FROM TRANSAC WHERE PRICE>=50;

SELECT PRODUCTDESC FROM TRANSAC WHERE PRICE>=50 AND PRICE<=100;
SELECT * FROM TRANSAC WHERE PRICE>=50 AND PRICE<=100;
SELECT PRODUCTID, PRODUCTDESC FROM TRANSAC WHERE PRICE BETWEEN 50 AND 100;
SELECT * FROM TRANSAC WHERE PRODUCTDESC IN ('TSHIRT','SHIRT');

SELECT * FROM TRANSAC ORDER BY PRICE; -- DEFAULT IS ASCENDING
SELECT * FROM TRANSAC ORDER BY PRICE DESC ;


SELECT * FROM TRANSAC ORDER BY PRICE, DISC_PEC;
SELECT * FROM TRANSAC ORDER BY PRICE DESC, DISC_PEC;

SELECT DISTINCT PRODUCTID FROM TRANSAC;

INSERT INTO TRANSAC       --FILL IN INFORMATION INTO THE TABLE CREATED (HERE ITS TRANSACACION TABLE)
VALUES                  -- ALL VALUES SHOULD BE STORED IN ORDER OF THE COLUMN NAMES
(1010,'P1','TSHIRT',NULL,NULL)
;

SELECT * FROM TRANSAC;
SELECT * FROM TRANSAC WHERE PRICE IS NOT NULL;
SELECT *, ISNULL(PRICE,50) AS UPDT_PRC FROM TRANSAC;
SELECT *, COALESCE(PRICE,100) AS UPDT_PRC2 FROM TRANSAC;

SELECT *
	, CASE
	WHEN PRICE>100 THEN 'HIGH'
	WHEN PRICE>50 AND PRICE<100 THEN 'MEDIUM'
	ELSE 'LOW'
	END AS PRICE_CLASS
	FROM TRANSAC;

SELECT *
		, CASE 
		WHEN PRODUCTDESC IN ('TSHIRT','SHIRT') THEN 'MENS WEAR'
		WHEN PRODUCTDESC IN ('SAREE','TOP') THEN 'WOMEN WEAR'
		WHEN PRODUCTDESC IN ('PANT') THEN 'UNISEX'
		ELSE 'UNK'
		END AS PROD_CLASS
		FROM TRANSAC;


SELECT COUNT(*) FROM TRANS WHERE PRICE>100;

SELECT PRODUCTDESC, COUNT(PRODUCTID) AS NUM_OF_PRODS FROM TRANSAC GROUP BY PRODUCTDESC;
SELECT PRODUCTDESC, COUNT(DISTINCT PRODUCTID) AS NUM_OF_PRODS FROM TRANSAC GROUP BY PRODUCTDESC;
SELECT PRODUCTDESC, COUNT(PRODUCTID) AS NUM_OF_PRODS FROM TRANSAC GROUP BY PRODUCTDESC HAVING COUNT(PRODUCTID)>3;

------------------
--ALTER TABLE TRANSAC DROP DISC_PER;
ALTER TABLE dbo.TRANSAC DROP COLUMN PRICE;

--ALTER TABLE dbo.TRANSAC drop constraint DISC_PER;

TRUNCATE TABLE TRANSAC;

DROP TABLE TRANSAC;
