sp_configure 'show advanced options', 1;  
GO  
RECONFIGURE;  
GO  
sp_configure 'max server memory', 32768;   -- for 32 GB
GO  
RECONFIGURE;  
GO

--------------------------------------------------
--DROP TABLE TABLE_NAME;

CREATE DATABASE ECOMMERCE_PLATFORM;

USE ECOMMERCE_PLATFORM;

CREATE TABLE TRANSAC (     --SYNTAX FOR CREATING AN EMPTY TABLE , SPECIFY THE NAME OF THE TABLE NAME
TNXID INT PRIMARY KEY,     --ASSIGN APPROPRIATE DATATYPES TO THE COLUMNS CREATED (BASICALLY WHAT TYPE OF DATA YOU WANT TO STORE)
PRODUCTID VARCHAR(255),
PRODUCTDESC VARCHAR(255),
PRICE FLOAT
);

INSERT INTO TRANSAC       --FILL IN INFORMATION INTO THE TABLE CREATED (HERE ITS TRANSACION TABLE)
VALUES                  -- ALL VALUES SHOULD BE STORED IN ORDER OF THE COLUMN NAMES
(1001,'P1','TSHIRT',100.50), -- DATATYPES OF THE COLUMNS AND THE VALUES IN IT SHOULD BE SAME
(1002,'P2','SHIRT',50),
(1003,'P3','PANT',40),
(1004,'P4','SAREE',120),
(1005,'P5','TOP',110),
(1006,'P6','TSHIRT',60),
(1007,'P1','TSHIRT',90),
(1008,'P3','PANT',50),
(1009,'P7','TSHIRT',70)
;


SELECT * FROM TRANSAC; --VIEW THE ENTIRE TABLE WITH ALL THE INFORMATION/DATA

--USE TRANS;
ALTER TABLE TRANSAC ADD DISCOUNT INT ;   -- ADDING A NEW COLUMN 
--ALTER TABLE TRANS ADD QTY INT AFTER PRODUCTDESC;

--ALTER TABLE TRANS RENAME DISCOUNT TO DISC_PEC;  MYSQL SYNTAX
EXEC SP_RENAME 'TRANSAC.DISCOUNT', 'DISC_PEC', 'COLUMN';  --SQL SERVER SYNTAX   -- RENAMING COLUMN

--Alter table table_name modify column column_name varchar(30);  MYSQL SYNTAX
-- ALTER TABLE dbo.TRANS ALTER COLUMN TNXID VARCHAR (255);
SELECT * FROM TRANSAC;

UPDATE TRANSAC SET DISC_PEC=10 WHERE TNXID=1001;   -- SETTING VALUES IN THE NEW COLUMN CREATED AS PER THE UNIQUE KEY TNXID
UPDATE TRANSAC SET DISC_PEC=15 WHERE TNXID=1002;
UPDATE TRANSAC SET DISC_PEC=5 WHERE TNXID=1003;
UPDATE TRANSAC SET DISC_PEC=20 WHERE TNXID=1004;
UPDATE TRANSAC SET DISC_PEC=8 WHERE TNXID=1005;
UPDATE TRANSAC SET DISC_PEC=12 WHERE TNXID=1006;
UPDATE TRANSAC SET DISC_PEC=11 WHERE TNXID=1007;
UPDATE TRANSAC SET DISC_PEC=15 WHERE TNXID=1008;
UPDATE TRANSAC SET DISC_PEC=5 WHERE TNXID=1009;

SELECT * FROM TRANSAC;


SELECT TRANSAC.TNXID, TRANSAC.PRODUCTDESC FROM TRANSAC;
SELECT TNXID, PRODUCTDESC FROM TRANSAC;   -- SELECT ONLY SPECIFIC COLUMN/INFO FROM THE TABLE

SELECT TOP 2 * FROM TRANSAC;    -- HELPS YOU TO VIEW A SUBSET OF THE TABLE - YOU CAN SPECIFY HOW MANY ROWS YOU WANT TO SEE
--SELECT * FROM TRANS LIMIT 2;

SELECT * FROM TRANSAC WHERE PRICE>=50; 

SELECT productid        -- GOOD PRACTICE FOR WRITING QUERY
		, PRODUCTDESC
		, price
		--,DISC_PEC
		FROM TRANSAC  
			WHERE PRICE>=50;

SELECT PRODUCTDESC FROM TRANSAC WHERE PRICE>=50 AND PRICE<=100;    -- SET RANGE FOR FILTERING


SELECT * FROM TRANSAC WHERE PRICE>=50 AND PRICE<=100;

SELECT PRODUCTID, PRODUCTDESC FROM TRANSAC WHERE PRICE BETWEEN 50 AND 100;  -- ANOTHER WAY OF SETTING RANGE FOR FILERING

SELECT * FROM TRANSAC WHERE PRODUCTDESC IN ('TSHIRT','SHIRT');   -- SPECIFY AS PER WHAT VALUES YOU WANT TO FILTER 

SELECT *            --GETTING ALL COLUMNS 
		FROM TRANSAC 
			WHERE  --FILTERING OPERATIONS START
			PRODUCTID IN ('P1','P2','P3')    --FILTER 1
			AND PRICE>50   --FILTER 2 -- FOR ADDING MORE FILTERS USE AND
			AND DISC_PEC>10;  --FILTER 3

SELECT * FROM TRANSAC ORDER BY PRICE; -- DEFAULT IS ASCENDING
SELECT * FROM TRANSAC ORDER BY PRICE DESC;
